dynamique_orm/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

app_name = 'dynamique_orm'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^details/(?P<dish_id>[0-9]+)/$', views.details, name='details'),
    url(r'^order/(?P<dish_id>[0-9]+)/$', views.order, name='order'),
    url(r'^get_count_order/$', views.get_count_order, name='count_order'),
    url(r'^basket/$', views.BasketView.as_view(), name='basket'),
    url(r'^delete_order/(?P<order_id>[0-9]+)/$', views.delete_order, name='delete_order'),
    url(r'^validate_basket/$', views.validate_basket, name='validate_basket'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', views.logout_page, name='logout'),
    url(r'^register/$', views.register_page, name='register'),
]

web_project/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^dynamique_orm/', include('dynamique_orm.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dynamique_orm/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings
from model_utils import FieldTracker
from django.db.models import Sum
from django.contrib.auth.models import User


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Dish(models.Model):
    class Meta:
        verbose_name = 'Plat'

    name_text = models.CharField('Nom du plat',max_length=200)
    description_text = models.CharField('Description',max_length=500)
    price = models.DecimalField('Prix',max_digits=7, decimal_places=4)
    picture = models.ImageField(upload_to = '', default = 'default.jpg')

    def __str__(self):
        return self.name_text

    def get_picture(self):
        return u'<img src="%s" width="300"/>' % self.picture.url

    get_picture.short_description = 'Suggestion de présentation'
    get_picture.allow_tags = True

    def get_suggested_price(self):
        sum = 0
        for receipe in Receipe.objects.filter(dish_id = self.id):
            sum = sum + receipe.quantity * receipe.ingredient.getprice()
        #Il faut bien faire un petit peu de marge =)
        return float(sum) * 1.5

    def is_available(self):
        is_available = 1
        for receipe in Receipe.objects.filter(dish_id = self.id):
            if receipe.quantity > receipe.ingredient.quantity :
                is_available = 0
        return is_available

    get_suggested_price.short_description = 'Prix de vente conseillé '

    #Le nombre de plat disponnible
    def count_available(self):
        count_available = 99999
        for receipe in Receipe.objects.filter(dish_id = self.id):
            if receipe.ingredient.quantity//receipe.quantity < count_available :
                count_available = receipe.ingredient.quantity//receipe.quantity
        return count_available

    count_available.short_description = 'Nombre de plat disponnible '

class Financial(models.Model):
    class Meta:
        verbose_name = 'Flux financier'

    beneficiary = models.IntegerField()
    amount = models.DecimalField('Montant',max_digits=9, decimal_places=4)
    paid_date = models.DateField('Date du transfert',auto_now_add=True, blank=True)
    description_text = models.CharField('Description',max_length=500)

    def __str__(self):
        return self.description_text

    def getamount(self):
        beneficiary = self.beneficiary
        if beneficiary == 1:
            return u'<b style="color: #FF0000;">-%s</b>' % self.amount
        return u'<b style="color: #00FF00;">%s</b>' % self.amount

    getamount.allow_tags = True
    getamount.short_description = 'Montant'

class Ingredient(models.Model):
    class Meta:
        verbose_name = 'Ingrédient'

    name_text = models.CharField('Nom de l\'ingrédient',max_length=200)
    price = models.DecimalField('Prix',max_digits=7, decimal_places=4)
    quantity = models.IntegerField('Quantité en stock',validators=[MaxValueValidator(999999),MinValueValidator(0)])
    unit_type = models.IntegerField('Type d\'unité')
    #Pour comparer les valeurs et facturer les achats/ ventes
    tracker = FieldTracker()

    def __str__(self):
        return self.name_text

    def getquantity(self):
        return self.quantity

    getquantity.short_description = 'Quantité en stock'

    def getunitype(self):
        unit_type = self.unit_type
        if unit_type == 0:
            return "Unité(s)"
        elif unit_type == 1:
            return "Gramme(s)"
        elif unit_type == 2:
            return "Centilitre(s)"

    getunitype.short_description = 'Unité'

    def getprice(self):
        return self.price

    def save(self):
        previous = self.tracker.previous('quantity')
        current = self.quantity
        if self.tracker.has_changed('quantity'):
            total = Financial.objects.filter(beneficiary=0).aggregate(sum=Sum('amount'))['sum'] - Financial.objects.filter(beneficiary=1).aggregate(sum=Sum('amount'))['sum']
            cost = abs(current - previous) * float(self.price)
            if (current - previous) > 0:
                #Facturation
                Financial.objects.create(beneficiary=1,amount=cost,description_text="Achat de "+str(abs(current - previous))+" "+self.getunitype()+" de "+self.name_text)
                if(total < cost) :
                    print("Attention la banque va pas apprécier")
            else:
                Financial.objects.create(beneficiary=0,amount=cost,description_text="Vente de "+str(abs(current - previous))+" "+self.getunitype()+" de "+self.name_text)
        models.Model.save(self)

class Receipe(models.Model):
    class Meta:
        verbose_name = 'Recette'
        verbose_name_plural = 'Recette'

    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.IntegerField('Quantité necessaire')

    def __str__(self):
        return ""

    def getquantity(self):
        if self.ingredient.getquantity() >= self.quantity:
            return u'<b style="color: #00FF00;">%s</b>' % self.ingredient.getquantity()
        return u'<b style="color: #FF0000;">%s</b>' % self.ingredient.getquantity()

    getquantity.short_description = 'Quantité en stock'
    getquantity.allow_tags = True 

    def getunitype(self):
        return self.ingredient.getunitype()

    getunitype.short_description = 'Unité'

class Order(models.Model):
    class Meta:
        verbose_name = 'Commande'

    user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name="Login du client")
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE,verbose_name="Nom du plat")
    quantity = models.IntegerField('Quantité commandée')
    order_date = models.DateField('Date de la commande',auto_now_add=True, blank=True)
    is_validate = models.IntegerField(default=0)

    def getstatus(self):
        if self.is_validate == 0 :
            return "En attente de validation"
        return "Payée"
    
    getstatus.short_description='Statut de la commande'

    def save(self):
        #current = self.quantity
        previous_order = Order.objects.filter(user_id=self.user.id).filter(is_validate=0).filter(dish=self.dish)
        if previous_order:
            previous_order.update(quantity=previous_order[0].quantity + int(self.quantity))
        else :
            models.Model.save(self)

dynamique_orm/forms.py
from django import forms
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password',
                          widget=forms.PasswordInput())
    password2 = forms.CharField(label='Password (Again)',
                        widget=forms.PasswordInput())

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
        raise forms.ValidationError('Passwords do not match.')

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Username is already taken.')

class OrderForm(forms.Form):
    dish = forms.IntegerField(required=False, widget=forms.HiddenInput())
    quantity = forms.IntegerField()

dynamique_orm/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth import logout
from dynamique_orm.forms import *
from django.template import RequestContext
from django.http import JsonResponse

from .models import *

class IndexView(generic.ListView):
    template_name = 'dynamique_orm/index.html'
    context_object_name = 'list_of_dishes'

    def get_queryset(self):
        return Dish.objects.order_by('-name_text')

class BasketView(generic.ListView):
    context_object_name = 'list_of_orders'
    template_name = 'dynamique_orm/basket.html'

    def get_queryset(self):
	    return Order.objects.filter(user_id=self.request.user.id).filter(is_validate=0).order_by('-order_date')

def details(request,dish_id):
    dish = get_object_or_404(Dish, pk=dish_id)
    return render(request,'dynamique_orm/details.html',context={"dish": dish})

def order(request,dish_id):
    quantity = request.POST['quantity']
    if is_available_dish(dish_id,quantity) and int(quantity) > 0:
        order = Order(user_id=request.user.id,dish_id=dish_id,quantity=quantity)
        order.save()
        set_ingredients(dish_id,quantity)
    return HttpResponseRedirect(reverse('dynamique_orm:index', args=()))

#Web-service AJAX sécurisé par CSRF-TOKEN par Django
def get_count_order(request):
    count_order = 0
    if request.method == 'POST':
        response_data ={}
        count_order = Order.objects.filter(user_id=request.POST['user']).filter(is_validate=0).count()

    response_data['count_order'] = count_order

    return JsonResponse(response_data)

def delete_order(request,order_id):
    if request.method == 'POST':
        response_data ={}
        order = Order.objects.get(pk=order_id)
        if order :
            free_ingredients(order.dish_id,order.quantity)
            order.delete()

    return HttpResponseRedirect(reverse('dynamique_orm:basket', args=()))

def validate_basket(request):
    if request.method == 'POST':
        response_data ={}
        orders = Order.objects.filter(user_id=request.user.id).filter(is_validate=0)
        for order in Order.objects.filter(user_id=request.user.id).filter(is_validate=0):
            Financial.objects.create(beneficiary=0,amount=(order.quantity * order.dish.price),description_text="Vente de "+str(order.quantity)+" "+str(order.dish.name_text)+" à "+request.user.username)
            Order.objects.filter(pk = order.id).update(is_validate = 1)            
            #order.update(is_validate=1)
            print("okay")

    return HttpResponseRedirect(reverse('dynamique_orm:index', args=()))

def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse('dynamique_orm:login', args=()))

def register_page(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(username=form.cleaned_data['username'],password=form.cleaned_data['password1'],email=form.cleaned_data['email'],first_name=form.cleaned_data['first_name'],last_name=form.cleaned_data['last_name'])
            return HttpResponseRedirect(reverse('dynamique_orm:login', args=()))
    form = RegistrationForm()
    return render(request, 'registration/register.html', {'form': form})

def is_available_dish(dish_id,quantity=1):
    is_available = 1
    for receipe in Receipe.objects.filter(dish_id = dish_id):
        if receipe.quantity > receipe.ingredient.quantity * int(quantity) :
            is_available = 0
    return is_available

def set_ingredients(dish_id,quantity):
    for receipe in Receipe.objects.filter(dish_id = dish_id):
        ingredient = Ingredient.objects.filter(pk=receipe.ingredient_id)
        if ingredient :
            ingredient.update(quantity=(ingredient[0].quantity - int(quantity) * receipe.quantity))

def free_ingredients(dish_id,quantity):
    for receipe in Receipe.objects.filter(dish_id = dish_id):
        ingredient = Ingredient.objects.filter(pk=receipe.ingredient_id)
        if ingredient :
            ingredient.update(quantity=(ingredient[0].quantity + int(quantity) * receipe.quantity))

dynamique_orm/templates/dynamique_orm/basket.html
{%extends "base.html" %}
{%block title %}Panier{% endblock %}
{%block head %}Mon panier{% endblock %}
{%block content %}

{% if user.username %}
    {% if list_of_orders %}
	        {% for order in list_of_orders %}
		    {% if order.dish.is_available == 1 %}
			    <!--<li>
                    <div style="background-color: #fff; margin: 10px;">{{ order.dish.name_text }}|{{ order.dish.description_text }}|<div class="item" value="{% widthratio order.dish.price 1 order.quantity %}"></div>|<img src="{{ order.dish.picture.url }}" width="300"/></div>|{{ order.quantity }}
			    </li>-->
                <div class="col s12 m7">
	                <div class="card horizontal">
		                <div class="card-image">
			                <img style="width:420px" src="{{ order.dish.picture.url }}">
		                </div>
		                <div class="card-stacked">
			                <div class="card-content">
                                <form id="delete{{order.id}}" action="{% url 'dynamique_orm:delete_order' order.id %}" method="post">
				                    {% csrf_token %}
                                    <button style="position : absolute; right: 10px; top: 30px;" type="submit" class="btn-floating btn-large waves-effect waves-light red"><i style="font-size: 40px" class="material-icons">delete_forever</i></button>
                                </form>
            	                <h4 class="header">{{ order.dish.name_text }}</h4>
                                <div class="grey-text text-darken-1 quantity_item" value="{{order.quantity}}">Quantité = {{order.quantity}}</div>
                                <div class="grey-text text-darken-1 price_item" value="{% widthratio order.dish.price 1 order.quantity %}">Sous total = {% widthratio order.dish.price 1 order.quantity %} €</div>
                                <h5 class="header">Description : </h5>
                                <div value="{% widthratio order.dish.price 1 order.quantity %}">{{ order.dish.description_text }}</div>
			                </div>
		                </div>
	                </div>
                </div>
		    {% endif %}
	        {% endfor %}
            <br>
            <form style="text-align: right" action="{% url 'dynamique_orm:validate_basket' %}" method="post">
	            {% csrf_token %}
                <button id="form_validate" class="btn waves-effect waves-light" type="submit" name="action"></button>
            </form>
	{% else %}
	    <p>Votre panier est vide.</p>
	{% endif %}
    {% load static %}
    <script src="{% static 'dynamique_orm/sum_price.js' %}"></script> 
{% else %}
	<h3 class="page-title">Cette page est restreinte aux utilisateurs connectés</h3>
{% endif %}

{% endblock %}

dynamique_orm/templates/dynamique_orm/details.html
{%extends "base.html" %}
{%block title %}Commander{% endblock %}
{%block head %}{{ dish.name_text }}{% endblock %}
{%block content %}

{% if user.username %}
    {% if dish.is_available == 1 %}
        <div class="gallery row">
            <div class="col s12 m6 gallery-item gallery-expand gallery-filtergallery-fillscreen" data-type="sacred-geometry" data-tag="hexagon" data-size="small" data-fillscreen="true">
                <div class="placeholder">
                    <div class="gallery-curve-wrapper">
                        <div class="card">
                            <div class="card-image">
                                <a class="gallery-cover gray">
                                    <img class="responsive-img" src="{{ dish.picture.url }}" alt="Hexagon" crossorigin="anonymous">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card col s12 m6">
                <div class="card-content">
                    <div class="product-description">
                        <h4>Description du plat :</h4>
                        <div class="rte">
                            <span>{{ dish.description_text }}</span>
                        </div>
                        <h4>Commander :</h4>
                        <form action="{% url 'dynamique_orm:order' dish.id%}" method="post" autocomplete="off">
                            {% csrf_token %}
                            <input id="form_quantity" name = "quantity" type="number" value="0" min="0" max="{{ dish.count_available }}" onchange="refresh_button()"/>
                            <button id="form_validate" class="btn waves-effect waves-light" price="{{ dish.price }}" type="submit" disabled name="action">Choisissez la quantité</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% load static %}
        <script src="{% static 'dynamique_orm/manage_button_cost.js' %}"></script> 
        <!--Manque d'ingrédients-->        
    {% else %}
        Ce plat est victime de son succès, pour commander un autre plat rendez vous à la page d'acceuil
    {% endif %}
{% else %}
	<h3 class="page-title">Cette page est restreinte aux utilisateurs connectés</h3>
{% endif %}
{% endblock %}

dynamique_orm/templates/dynamique_orm/index.html
{%extends "base.html" %}
{%block title %}Accueil{% endblock %}
{%block head %}Accueil{% endblock %}
{%block content %}

{% if user.username %}
	{% if list_of_dishes %}
		<div class="row">
	    {% for dish in list_of_dishes %}
			<!--<li><div onclick="location.href='{% url 'dynamique_orm:details' dish.id %}'" style=" margin: 10px; ">{{ dish.name_text }}|{{ dish.description_text }}|{{ dish.price }}|<img src="{{ dish.picture.url }}" width="500"/></div></li>-->
		    <div class="col s5 m4">
		        <div class="card">
		            <div class="card-image">
                        {% if dish.is_available == 1 %}
		                    <img class="materialboxed" width="300" src="{{ dish.picture.url }}">
                        {% else %}
		                    <img class="materialboxed" style="opacity: 0.6;" width="300" src="{{ dish.picture.url }}">
	                    {% endif %}
	                </div>
	                <div class="card-content">
		                <p style="white-space: nowrap; overflow: hidden;text-overflow: ellipsis;">{{ dish.name_text }}</p>
		                </div>
		                <div class="card-action">
                		<!--Est disponnible-->
	                    {% if dish.is_available == 1 %}
		                    <a href="{% url 'dynamique_orm:details' dish.id %}">En savoir plus</a>
                        {% else %}
		                    <a class="red-text text-darken-2">Victime de son succès</a>
	                    {% endif %}
		            </div>
		        </div>
		    </div>
	    {% endfor %}
        </div>
	{% else %}
	    <p>Aucun plat n'est disponnible à la vente, veuillez nous excuser pour la gêne occasionnée.</p>
	{% endif %}
{% else %}
	<h3 class="page-title">Cette page est restreinte aux utilisateurs connectés</h3>
{% endif %}

{% endblock %}